In [41]:
from aocd import get_data

puzzle_input = get_data(day=18, year=2015)
puzzle_input = puzzle_input.split("\n")

In [44]:
import numpy as np

grid_puzzle = np.array([
    [1 if x == "#" else 0 for x in row]
    for row in puzzle_input
])

print(grid_puzzle[:5, :5])

[[1 1 1 0 1]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 1 1]
 [0 1 1 1 0]]


In [52]:
example = """
.#.#.#
...##.
#....#
..#...
#.#..#
####..
""".strip().split("\n")

grid_example = np.array([
    [1 if x == "#" else 0 for x in row]
    for row in example
])

grid_example

array([[0, 1, 0, 1, 0, 1],
       [0, 0, 0, 1, 1, 0],
       [1, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0, 0],
       [1, 0, 1, 0, 0, 1],
       [1, 1, 1, 1, 0, 0]])

In [43]:
def construct_sum_function(grid):
    grid = grid.copy()
    S = grid.cumsum(axis=0).cumsum(axis=1)
    Mx = S.shape[0] -1
    My = S.shape[1] -1

    def sum_neighbors(i, j):
        x0 = max(i - 1, 0)
        x1 = min(i + 1, Mx)
        y0 = max(j - 1, 0)
        y1 = min(j + 1, My)

        return (
            S[x1, y1]
            - (S[x1, y0] if j > 1 else 0)
            - (S[x0, y1] if i > 1 else 0)
            + (S[x0, y0] if i > 1 and j > 1 else 0)
            - grid[i, j]
        )
    
    return sum_neighbors


def next_grid(grid):
    sum_neighbors = construct_sum_function(grid)

    for i in range(grid.shape[0]):
        for j in range(grid.shape[1]):
            n_neighbors = sum_neighbors(i, j)

            if grid[i, j] == 1 and (2 < n_neighbors or n_neighbors > 3):
                grid[i, j] = 0
            elif grid[i, j] == 0 and n_neighbors == 3:
                grid[i, j] = 1
            
    return grid

In [61]:
grid[0:1, 0:1]

array([[0]])

In [64]:
def next_grid(grid):
    new_grid = grid.copy()

    Mx = grid.shape[0] -1
    My = grid.shape[1] -1

    for i in range(grid.shape[0]):
        for j in range(grid.shape[1]):
            n_neighbors = grid[
                max(0, i-1):min(Mx, i+1)+1, 
                max(0, j-1):min(My, j+1)+1
            ].sum() - grid[i,j]

            if grid[i, j] == 1:
                if n_neighbors not in (2, 3):
                    new_grid[i, j] = 0
            else:
                if n_neighbors == 3:
                    new_grid[i, j] = 1
            
    return new_grid

In [65]:
grid = grid_example.copy()
print(grid)

for _ in range(4):
    grid = next_grid(grid)
    print(grid)

grid.sum()

[[0 1 0 1 0 1]
 [0 0 0 1 1 0]
 [1 0 0 0 0 1]
 [0 0 1 0 0 0]
 [1 0 1 0 0 1]
 [1 1 1 1 0 0]]
[[0 0 1 1 0 0]
 [0 0 1 1 0 1]
 [0 0 0 1 1 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 1 1 0 0]]
[[0 0 1 1 1 0]
 [0 0 0 0 0 0]
 [0 0 1 1 1 0]
 [0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]]
[[0 0 0 1 0 0]
 [0 0 0 0 0 0]
 [0 0 0 1 0 0]
 [0 0 1 1 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 1 1 0 0]
 [0 0 1 1 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


4

In [66]:
grid = grid_puzzle.copy()

for _ in range(100):
    grid = next_grid(grid)

grid.sum()

821

In [67]:
def next_grid(grid):
    Mx = grid.shape[0] -1
    My = grid.shape[1] -1

    grid[0, 0] = 1
    grid[Mx, 0] = 1
    grid[Mx, My] = 1
    grid[0, My] = 1

    new_grid = grid.copy()

    for i in range(grid.shape[0]):
        for j in range(grid.shape[1]):
            n_neighbors = grid[
                max(0, i-1):min(Mx, i+1)+1, 
                max(0, j-1):min(My, j+1)+1
            ].sum() - grid[i,j]

            if grid[i, j] == 1:
                if n_neighbors not in (2, 3):
                    new_grid[i, j] = 0
            else:
                if n_neighbors == 3:
                    new_grid[i, j] = 1

    new_grid[0, 0] = 1
    new_grid[Mx, 0] = 1
    new_grid[Mx, My] = 1
    new_grid[0, My] = 1
            
    return new_grid

In [69]:
grid = grid_example.copy()
print(grid)

for _ in range(5):
    grid = next_grid(grid)

grid.sum()

[[0 1 0 1 0 1]
 [0 0 0 1 1 0]
 [1 0 0 0 0 1]
 [0 0 1 0 0 0]
 [1 0 1 0 0 1]
 [1 1 1 1 0 0]]


17

In [70]:
grid = grid_puzzle.copy()

for _ in range(100):
    grid = next_grid(grid)

grid.sum()

886